
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css'
import NavBar from "@/components/navbar";
import Header from "@/components/header";
import StyledComponentsRegistry from "@/lib/styledComponentsRegistry";
import StoreProvider from "./StoreProvider";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const dynamic = 'force-static';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
        <StyledComponentsRegistry>
        <Header />
        <NavBar />
        {children}
        </StyledComponentsRegistry>
        </StoreProvider>
        </body>
    </html>
  );
}
